### ISSUE TITLE
Using S3FS plug-in with kubernetes VPC cluster does not need VRF to be enabled

### ISSUE THREAD

**Issue by Mallear** [ibm-cloud-docs/containers#2492] opened 2020-04-07 08:50 UTC
Hello,

In this documentation page : https://cloud.ibm.com/docs/containers?topic=containers-object_storage#install_cos it's mentionned that we need to enable VRF if installing IBM Cloud Object Storage plug-in in a VPC Cluster.

I've tried without VRF enabled and it works. I guess the right sentence should be "if installing IBM Cloud Object Storage plug-in in a non-VPC Cluster" ?

**Comment by Mallear** [comment] 2020-04-07 15:00
Seems that the part which need to create a new storage class for VPC cluster is not relevant anymore (https://cloud.ibm.com/docs/containers?topic=containers-object_storage#customized_storageclass_vpc) as the endpoint is already the good one out of the box:

```
$ kubectl get storageclass ibmc-s3fs-cold-cross-region -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2020-04-07T14:26:58Z"
  labels:
    app: ibmcloud-object-storage-plugin
    chart: ibm-object-storage-plugin-1.1.4
    heritage: Helm
    release: ibm-object-storage-plugin
  name: ibmc-s3fs-cold-cross-region
  resourceVersion: "1596067"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/ibmc-s3fs-cold-cross-region
  uid: e03c8eca-2ef4-40ad-86df-20e1fe97584d
parameters:
  ibm.io/chunk-size-mb: "16"
  ibm.io/curl-debug: "false"
  ibm.io/debug-level: warn
  ibm.io/iam-endpoint: https://iam.bluemix.net
  ibm.io/kernel-cache: "false"
  ibm.io/multireq-max: "20"
  ibm.io/object-store-endpoint: https://s3.direct.fra.eu.cloud-object-storage.appdomain.cloud
  ibm.io/object-store-storage-class: eu-cold
  ibm.io/parallel-count: "2"
  ibm.io/s3fs-fuse-retry-count: "5"
  ibm.io/stat-cache-size: "100000"
  ibm.io/tls-cipher-suite: AESGCM
provisioner: ibm.io/ibmc-s3fs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

May need the confirmation from technical people from IBMCloud, but it seems we do not need to create a new StorageClass.

**Comment by Nadine2016** [comment] 2020-04-09 12:39
@Mallear so we confirmed with out dev lead that the storage classes are now correctly set up with the `direct` endpoint. I will remove this extra step. for VRF, the team was saying it is still required, but they will verify without VRF. so it might be that we take out this note as well.

**Comment by Mallear** [comment] 2020-04-09 12:53
@Nadine2016  I've double checked, I haven't activated VRF. Waiting for information from IBM team :)

**Comment by Nadine2016** [comment] 2020-04-09 14:46
@Mallear so it turns out that you used to have it enabled because we created the `private` endpoints in the storage classes. Those endpoints did not work, which is why we had this additional topic in place for how to create the `direct` storage classes. now that we create the `direct` endpoints automatically, it seems that the `direct` endpoints are in a different network that does not need VRF.  the team still wants to verify that so I am leaving this note in place until they confirmed it. But from what you said and what they found out, it is very likely that we will remove this note within the next week.

**Comment by Mallear** [comment] 2020-04-23 08:15
@Nadine2016 Do you have any news about this issue ?

**Comment by Nadine2016** [comment] 2020-04-24 16:34
@Mallear the dev team was not able to verify the VRF setting yet. But they told me that they wanted to work on that this week or early next week. So I am hoping that I have an answer latest by next week.

**Comment by Rachael-Graham** [comment] 2020-05-07 14:27
I've made the change to remove the VRF requirement. This change will be pushed to prod this week or early next week. Closing out

**Closed by Rachael-Graham** 2020-05-07 14:27 UTC
